jobs:
  - job: 'Build and test'
    pool:
      vmImage: 'ubuntu-16.04'
    container: 'rust:latest'
    steps:
      - script: cargo build --all
        displayName: Cargo build
      - script: cargo test --all
        displayName: Cargo test
