[package]
name = "foolang"
version = "0.2.0"
authors = ["Nikodemus Siivola <nikodemus@random-state.net>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "*"
num = "*"
clap = "*"
rouille = "*"
webbrowser = "*"

[target.'cfg(unix)'.dependencies]
libc = "*"

[target.'cfg(windows)'.dependencies]
winapi = "*"

[dev-dependencies]
assert_cmd = "*"
predicates = "*"
serde_json = "*"
pretty_assertions = "0.6.1"
