[package]
name = "foolang"
version = "0.1.0"
authors = ["Nikodemus Siivola <nikodemus@random-state.net>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop = "0.17.0"

[dependencies]
lalrpop-util = "0.17.0"
regex = "1"
lazy_static = "*"
num = "*"
clap = "*"
libc = "*"

[dev-dependencies]
assert_cmd = "*"
predicates = "*"
