#ifndef __CONFIG_H_
#define __CONFIG_H_

#define FOO_ACTOR_QUEUE_INITIAL_CAPACITY 8
#define FOO_ACTOR_STACK_BYTES 1024
#define FOO_ACTOR_TIMESLICE 1024
#define FOO_SYSTEM_LOCK_SPIN_COUNT 1024
#define FOO_EXECUTOR_INTERRUPT_DELAY 10

#endif // __CONFIG_H_
