name: Auto approve
on: pull_request_target

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: hmarr/auto-approve-action@v2
          if: github.actor == 'nikodemus'
          with:
            github-token: "${{ secrets.GITHUB_TOKEN }}"
