name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash

env:
  # Transpiled code currently leaks like a sieve, intentionally
  # never freeing anything.
  ASAN_OPTIONS: detect_leaks=0
  UBSAN_OPTIONS: print_stacktrace=1
  RUST_BACKTRACE: 1

jobs:

  test-host:
    name: "Test booststrap host"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
       - uses: actions/checkout@v2

       - name: Rust toolchain
         uses: actions-rs/toolchain@v1
         with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

      - name: Test large
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --ignored

      - name: Upload bootstrap host
        uses: actions/upload-artifact@v2
        with:
            name: foo-${{ GITHUB_SHA }}
            path: target/debug/foo*
        if: ${{ runner.os == 'Windows' }}

  test-foolang:
    name: "Test target"
    needs: test-host
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      # Clang is installed on the Windows image, but is not in path.
      - name: Extend path
        run: echo 'C:\msys64\mingw64\bin' >> $GITHUB_PATH
        if: ${{ runner.os == 'Windows' }}

      - name: Clang version
        run: clang --version

      - name: Download boostrap host
        uses: actions/download-artifact@v2
        with:
          name: foo-${{ GITHUB_SHA }}

      - name: Test Foolang
        run: ./foo -- foo/impl/test_foolang.foo --use=foo/lib

      - name: Test Prelude
        run: ./foo -- foo/impl/test_prelude.foo --use=foo/lib

      - name: Test Transpile
        run: ./foo -- foo/impl/test_transpile.foo --use=foo/lib

  test-self-compile:
    name: "Test self compile"
    needs: test-host
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clang version
        run: clang --version

      - name: Download boostrap host
        uses: actions/download-artifact@v2
        with:
          name: foo-${{ GITHUB_SHA }}

      - name: Build compiler while running on bootstrap host
        run: ./foo foo/compile.foo ./bootstrap-fooc

      - name: Build compiler with compiler
        run: ./bootstrap-fooc foo/compile.foo ./fooc

  test-foolang-mode:
    name: "Test foolang Emacs mode"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Emacs
        run: |
          sudo add-apt-repository -y ppa:kelleyk/emacs
          sudo apt-get install -y emacs26-nox

      - name: Test foolang-mode
        run: ./test-elisp.sh
